### ISSUE TITLE
Document further Hoodiecrow usage from clients trying to send/receive emails using Hoodiecrow server

### ISSUE THREAD

**Issue by balteo** [andris9/hoodiecrow#20]
Hi Andris,

I have just opened a post on SO here: http://stackoverflow.com/questions/33828525. I have also created the "Hoodiecrow" tag on SO!

I am not sure how to configure my application to use my instance of Hoodiecrow in order to send email...

Which host should I use: `localhost` or `imap.localhost`?

Can you please help me?

**Comment by andris9** [comment]
Hoodiecrow creates a local dummy IMAP server suitable for testing, it is not meant for actual mail processing. If you run the [example server](https://github.com/andris9/hoodiecrow/blob/master/examples/complete.js) then you can connect to it at hostname=localhost, port=1143 as to any other IMAP server

**Comment by balteo** [comment]
Andris,
What do you mean by "it is not meant for actual mail processing"?
Can I still read and parse an email sent to Hoodiecrow?
Regards,
Julien.

2015-11-20 16:05 GMT+01:00 Andris Reinman <notifications@github.com>:

**Comment by andris9** [comment]
You should be able to use it as a "normal" IMAP server. Once you restart the process the entire state is gone, you have lost all messages, folder data and such. This is intentional design – hoodiecrow is meant for client integration testing. Let's say you are trying to build a new IMAP client and you want to test it somehow and create some automated tests. So you fire up a hoodiecrow instance, run your tests and close the server. Next time you start the tests you don't have any accidental leftovers around from previous runs, so you can start from a clean state.

**Comment by andris9** [comment]
If you are only interested in receiving and sending and not storing messages (IMAP itself does not "receive" or "send" anything, IMAP is storage for emails), you should look into SMTP solutions, for example [Haraka SMTP](https://haraka.github.io/)

**Comment by balteo** [comment]
Thanks a lot Andris.

2015-11-20 17:14 GMT+01:00 Andris Reinman <notifications@github.com>:
